slam_toolbox:
  ros_parameters:
    max_laser_range: 3.5
    map_update_intervals: 0.01
    loop_match_minimum_response_fine: 0.8
    linear_update: 0.4
    angular_update: 0.1
  global_costmap:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 100.0  # Set your desired update frequency in Hz